# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZAKER Pro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZAKER Pro

  pod 'SnapKit', '~> 4.0.0'

  target 'ZAKER ProTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZAKER ProUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
